General Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

they are equal, or

one of them is 1

In [1]:
import numpy as np

In [3]:
a = np.array([0.0, 10.0, 20.0, 30.0])
display(a)
b = np.array([1.0, 2.0, 3.0])
display(b)
c=a[:, np.newaxis]
display(c)
d = c + b
display(d)

array([ 0., 10., 20., 30.])

array([1., 2., 3.])

array([[ 0.],
       [10.],
       [20.],
       [30.]])

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])